### ISSUE TITLE
A small spelling mistake in scripts

### ISSUE THREAD

**Issue by Chen-SHuangHui** [saorisakaue/Genotype-dimensionality-reduction#1]
Dear Dr. Sakaue:

Hi.

Thanks a lot for  your code of dimensionality reduction, which I have used for my own analysis. 
But I found a small spelling mistake in the scripts.

In the script 01_pre_genotype.sh, line 5
GENPTYPE="$1"
I suppose that the variable name "GENPTYPE" should have been written as "GENOTYPE".

Best wishes

Shuanghui Chen

**Comment by saorisakaue** [comment]
Hi Shuanghui,
Thank you so much for kindly pointing out my stupid typo!
I have just updated with the corrected script of 01_pre_genotype.sh.
I hope our work helps your analysis.
Best,
Saori
